### ISSUE TITLE
MySQL 8 "rank" setup issues

### ISSUE THREAD

**Issue by brett-mcgirr** [tbar0970/jethro-pmm#715]
Hi, I'm installing Jethro for the first time and running into a few issues regarding the use of rank as a column name on MySQL.

Would you like a pull request for the changes I made to get it working?

If no, here's a list of files I've changed:
age_bracket.class.php line 41
person_group.class.php line 104
roster_role_assignment.class.php line 13
db_object.class.php lines 62 and 66
installer.class.php lines 183 and 194

**Comment by tbar0970** [comment]
Hi there, thanks for this. I'm happy to apply these manually rather than doing a PR. 
Just wanted to check: Are you running version 2.30.1? We fixed a bunch of these 'rank' issues recently, but perhaps there are some we missed.

**Comment by brett-mcgirr** [comment]
Thanks Tom. I was running the latest version from the master branch, but I've checked the zipped source in 2.30.1 and the issue is still there. To reproduce the problem, do a clean, initial install with a MySQL 8 backend.

**Comment by tbar0970** [comment]
Thanks for this, I've done a search and added backticks for the rank keyword in SQL in many places.
The tricky thing is that MariaDB *doesn't* have rank as a reserved word!
